services:
  # Main home assistant
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2026.2.1
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    user: "1000:1000"
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
    devices:
      - /dev/serial/by-id/usb-Nabu_Casa_ZBT-2_1CDBD45D72F8-if00:/dev/ttyUSB0
    restart: unless-stopped
    network_mode: host
    privileged: true

  # OpenThread Broad Router - Bridge between my network and the thread network
  otbr:
    image: ghcr.io/ownbee/hass-otbr-docker:latest
    container_name: otbr
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - /dev/serial/by-id/usb-Nabu_Casa_ZBT-2_1CDBD45D72F8-if00:/dev/adapter
    volumes:
      # The Bridge (The virtual network adapter)
      - /dev/net/tun:/dev/net/tun
      # The Memory
      - /opt/otbr/data:/var/lib/thread
    environment:
      - DEVICE=/dev/adapter
      - BAUDRATE=460800
      - OTBR_REST_PORT=8081
      - OTBR_WEB_PORT=8080
      - OTBR_WEB=1
      - FLOW_CONTROL=0
      - BACKBONE_IF=wlo1

  # Matter server - HA -> matter language
  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    network_mode: host
    volumes:
      - ./matter_server_data:/data
    restart: unless-stopped
    # Only needed if commissioning Thread/BLE via USB radio
    # privileged: true
    # devices:
    #   - /dev/ttyUSB1:/dev/ttyUSB1

    # Adguard
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:80" # host 3000 → container 80 Web UI - http://192.168.1.20:3000 (host machine IP Address)
      - "853:853/tcp" # DNS over TLS (optional)
      - "784:784/tcp" # DNS over HTTPS (optional)
    environment:
      - TZ=America/Chicago

  # Smart Home jobs
  smart_home_jobs:
    container_name: smart_home_jobs
    build:
      context: .
      dockerfile: Dockerfile.smart_home_jobs
    user: "1000:1000"
    volumes:
      - ./config/bash_wrappers:/logs
      - ./:/opt/smart_home
    environment:
      - PYTHONPATH=/opt/smart_home/src
      - SPOTIFY_REFRESH_TOKEN
      - SPOTIFY_CLIENT_SECRET
    entrypoint: [ "uv", "run", "/opt/smart_home/src/smart_home/jobs/q101_spotify.py" ]
    restart: "no"
