
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-sidebar/custom-sidebar-plugin.js?v=16.1.0

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# sensor:
#   - platform: comed_hourly_pricing
#     monitored_feeds:
#       - type: current_hour_average

# Notification Groups
notify:
  - name: "family_phones"
    platform: group
    services:
      - service: mobile_app_grants_iphone
      - service: mobile_app_nicoles_iphone_17


# Alerts
alert:
  left_garage_door:
    name: Left Garage Door was left open
    done_message: Left Garage Door is closing
    entity_id: cover.left_garage_door_door
    state: "open"
    repeat: 30
    can_acknowledge: true
    skip_first: true
    notifiers:
      - mobile_app_grants_iphone
  right_garage_door:
    name: Right Garage Door was left open
    done_message: Right Garage Door is closing
    entity_id: cover.right_garage_door_ratgdo_door
    state: "open"
    repeat: 30
    can_acknowledge: true
    skip_first: true
    notifiers:
      - mobile_app_grants_iphone
