order:
  - item: Home
    href: "/overview-grant/home"
    icon: mdi:home
    order: 1
  - new_item: true
    item: Security
    href: "/security"
    icon: mdi:shield-home
    order: 2
  - new_item: true
    item: Devices
    href: "/config/devices/dashboard"
    icon: mdi:devices
    order: 3
  - new_item: true
    item: Home Maintenance
    href: "/home-maintenance"
    icon: mdi:wrench
    order: 4
  - item: energy
    order: 5
  - item: activity
    order: 6
  - item: history
    order: 7
  - item: media-browser
    order: 8
  - item: home-network
    order: 9

  # Bottom Items
  - item: config
    name: Settings
    bottom: true
    order: 10
  - item: notifications
    bottom: true
    order: 11
  - item: profile
    bottom: true
    order: 12

  # Hide the ones you don't want to see
  - item: map
    hide: true
  - item: logbook
    hide: true
  - item: todo
    hide: true
